spring.application.name=MiniAmazon
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#TURN OFF SPING BANNER
spring.main.banner-mode=off
#reduce warning

# application.properties
logging.level.root=INFO


#port number
server.port=8069


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.type=redis